### ISSUE TITLE
разобраться со стикерпакам

### ISSUE THREAD

**Issue by regulyator** [dalayLama/memology-game-bot#1]
загрузить свой, проверить что можно генерировать динамически, проверить что можно менять в реалтайме

**Comment by regulyator** [comment]
Беда, боты не могут общаться с ботами, те мы не можем генерит стикерпаки автоматом:( есть идея попробовать через кнопки сделать

**Comment by regulyator** [comment]
> @regulyator я там начинал какую-то видяху на youtube смотреть про ботов, кратко пробежался по тому что чувак показывал: там на самом деле возможностей в интерфейсе дохера, вплоть до интерфейса оплаты(т.е. тебя не уводят в браузер, а прям в самом чате всплывающее окно нативное), так что, надо просто чуть плотнее посмотреть список возможностей интерфейса, на неделе посмотрю, какие варианты ещё есть.

А ссылки нет?)

**Comment by dalayLama** [comment]
> 

https://www.youtube.com/watch?v=IX3B87hqF4Y&t=1323s&ab_channel=MJC

**Comment by dalayLama** [comment]
> > @regulyator я там начинал какую-то видяху на youtube смотреть про ботов, кратко пробежался по тому что чувак показывал: там на самом деле возможностей в интерфейсе дохера, вплоть до интерфейса оплаты(т.е. тебя не уводят в браузер, а прям в самом чате всплывающее окно нативное), так что, надо просто чуть плотнее посмотреть список возможностей интерфейса, на неделе посмотрю, какие варианты ещё есть.
> 
> А ссылки нет?)

https://www.youtube.com/watch?v=IX3B87hqF4Y&t=1323s&ab_channel=MJC
